// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1XdiXX_Wr0QTOqBhfWMrB8eHF4RcDgqQ',
    appId: '1:419217161817:web:3b67f6ee5a7002231ffb48',
    messagingSenderId: '419217161817',
    projectId: 'poquidax-cfa90',
    authDomain: 'poquidax-cfa90.firebaseapp.com',
    storageBucket: 'poquidax-cfa90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRHxczM6_HJhQNYpggCqQLJCKV5KnWOcQ',
    appId: '1:419217161817:android:14eb35e94ff534d81ffb48',
    messagingSenderId: '419217161817',
    projectId: 'poquidax-cfa90',
    storageBucket: 'poquidax-cfa90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTBQVWdH0uUO1gg0ijevnmwtzDR8MpmUk',
    appId: '1:419217161817:ios:6e7dae9008b13e7d1ffb48',
    messagingSenderId: '419217161817',
    projectId: 'poquidax-cfa90',
    storageBucket: 'poquidax-cfa90.firebasestorage.app',
    iosBundleId: 'com.example.pokedax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTBQVWdH0uUO1gg0ijevnmwtzDR8MpmUk',
    appId: '1:419217161817:ios:6e7dae9008b13e7d1ffb48',
    messagingSenderId: '419217161817',
    projectId: 'poquidax-cfa90',
    storageBucket: 'poquidax-cfa90.firebasestorage.app',
    iosBundleId: 'com.example.pokedax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1XdiXX_Wr0QTOqBhfWMrB8eHF4RcDgqQ',
    appId: '1:419217161817:web:cd0a774c354975ba1ffb48',
    messagingSenderId: '419217161817',
    projectId: 'poquidax-cfa90',
    authDomain: 'poquidax-cfa90.firebaseapp.com',
    storageBucket: 'poquidax-cfa90.firebasestorage.app',
  );
}
