services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    environment:
      - FLASK_ENV=development

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
